export class CollectorStore{
  constructor(db){this.db=db;}
  async init(){await this.db.query(`CREATE TABLE IF NOT EXISTS promonet.collector_runs(niche_id TEXT PRIMARY KEY,last_started_at TIMESTAMPTZ,last_result TEXT,category_cursor INTEGER NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE promonet.collector_runs ADD COLUMN IF NOT EXISTS category_cursor INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS promonet.collector_rotation(id SMALLINT PRIMARY KEY CHECK(id=1),vertical_cursor INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS promonet.offer_previews(niche_id TEXT NOT NULL,item_id TEXT NOT NULL,title TEXT NOT NULL,price NUMERIC NOT NULL,original_price NUMERIC,image_url TEXT NOT NULL,product_url TEXT NOT NULL,affiliate_url TEXT,state TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(niche_id,item_id));
CREATE TABLE IF NOT EXISTS promonet.offer_publications(niche_id TEXT NOT NULL,item_id TEXT NOT NULL,published_day DATE NOT NULL DEFAULT CURRENT_DATE,affiliate_url TEXT NOT NULL,published_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(niche_id,item_id,published_day));`);}
  async claimDueNiches(niches){const claimed=[];for(const n of niches.filter(x=>x.enabled)){const r=await this.db.query(`INSERT INTO promonet.collector_runs(niche_id,last_started_at,last_result) VALUES($1,now(),'running') ON CONFLICT(niche_id) DO UPDATE SET last_started_at=now(),last_result='running',updated_at=now() WHERE promonet.collector_runs.last_started_at IS NULL OR promonet.collector_runs.last_started_at + ($2 * interval '1 minute') <= now() RETURNING niche_id`,[n.id,n.intervalMinutes]);if(r.rows.length)claimed.push(n);}if(claimed.length<2)return claimed;const rotation=await this.db.query(`INSERT INTO promonet.collector_rotation(id,vertical_cursor) VALUES(1,0) ON CONFLICT(id) DO UPDATE SET vertical_cursor=(promonet.collector_rotation.vertical_cursor+1)%$1 RETURNING vertical_cursor`,[claimed.length]);const start=Number(rotation.rows[0]?.vertical_cursor??0)%claimed.length;return claimed.slice(start).concat(claimed.slice(0,start));}
  async nextCategory(niche){const count=niche.categoryIds.length;const r=await this.db.query(`UPDATE promonet.collector_runs SET category_cursor=(category_cursor+1)%$2,updated_at=now() WHERE niche_id=$1 RETURNING (category_cursor-1+$2)%$2 AS selected_cursor`,[niche.id,count]);if(!r.rows.length)throw Error("collector_state_missing");return niche.categoryIds[Number(r.rows[0].selected_cursor)];}
  async recentItemIds(){const r=await this.db.query(`SELECT DISTINCT item_id FROM promonet.offer_publications WHERE published_at>=now()-interval '7 days'`);return new Set(r.rows.map(x=>x.item_id));}
  async savePreview(nicheId,c,state){await this.db.query(`INSERT INTO promonet.offer_previews(niche_id,item_id,title,price,original_price,image_url,product_url,state) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(niche_id,item_id) DO UPDATE SET title=EXCLUDED.title,price=EXCLUDED.price,original_price=EXCLUDED.original_price,image_url=EXCLUDED.image_url,product_url=EXCLUDED.product_url,state=EXCLUDED.state,updated_at=now()`,[nicheId,c.itemId,c.title,c.price,c.originalPrice,c.imageUrl,c.permalink,state]);}
  async completeRun(nicheId,result){await this.db.query(`UPDATE promonet.collector_runs SET last_result=$2,updated_at=now() WHERE niche_id=$1`,[nicheId,result]);}
  async markPublished(nicheId,itemId,url){await this.db.query(`WITH inserted AS (INSERT INTO promonet.offer_publications(niche_id,item_id,affiliate_url) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING item_id) UPDATE promonet.offer_previews SET state='published',affiliate_url=$3,updated_at=now() WHERE niche_id=$1 AND item_id=$2 AND EXISTS(SELECT 1 FROM inserted)`,[nicheId,itemId,url]);}
  async markReview(nicheId,itemId){await this.db.query(`UPDATE promonet.offer_previews SET state='review',updated_at=now() WHERE niche_id=$1 AND item_id=$2`,[nicheId,itemId]);}
}
