import test from "node:test";
import assert from "node:assert/strict";
import { collectOnce, collectDue } from "../collector.mjs";
const niche={id:"games",categoryId:"MLB1144",destinationGroup:"d@g.us",tag:"tag",limit:1,enabled:true};
const candidate={itemId:"MLB1",rank:0,title:"Console",status:"active",permalink:"https://produto.mercadolivre.com.br/MLB-1-console",imageUrl:"https://http2.mlstatic.com/a.jpg",price:100,originalPrice:150,categoryId:"MLB1144"};
function store(){const events=[];return{events,claimDueNiche:async()=>niche,recentItemIds:async()=>new Set(),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done;});return{promise,resolve};}
test("dry run persists preview without conversion or send",async()=>{const s=store();let external=0;const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>external++},evolution:{send:async()=>external++},dryRun:true});assert.equal(result,"simulated");assert.equal(external,0);assert.equal(s.events[0][3],"simulated");});
test("live run converts, sends image URL once, then publishes",async()=>{const s=store();const sends=[];const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async(job,media)=>sends.push({job,media})},dryRun:false});assert.equal(result,"published");assert.equal(sends.length,1);assert.equal(sends[0].media,candidate.imageUrl);assert.match(sends[0].job.text,/Publicidade/);assert.ok(s.events.some(e=>e[0]==="published"));});
test("ambiguous send is retained for review",async()=>{const s=store();const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{throw Error("send")}},dryRun:false});assert.equal(result,"review");assert.ok(s.events.some(e=>e[0]==="review"));});
test("session expiry raises the operator alert and successful conversion awaits restoration",async()=>{const required=[],restored=[],restoreGate=deferred(),restoreEntered=deferred();const alert={required:async()=>required.push(true),restored:async()=>{restored.push(true);restoreEntered.resolve();await restoreGate.promise;}};await assert.rejects(()=>collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>{throw Error("session_expired")}},evolution:{},sessionAlert:alert,dryRun:false}),/session_expired/);assert.equal(required.length,1);let sent=false;const collecting=collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{sent=true;}},sessionAlert:alert,dryRun:false});await restoreEntered.promise;assert.equal(restored.length,1);assert.equal(sent,false);restoreGate.resolve();assert.equal(await collecting,"published");assert.equal(sent,true);});

test("collectOnce publishes a valid affiliate offer when incident restoration persistence fails",async()=>{const s=store(),errors=[],sends=[];const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},sessionAlert:{required:async()=>{},restored:async()=>{throw Error("database-password=super-secret");}},logger:{info(){},error:event=>errors.push(event)},dryRun:false});assert.equal(result,"published");assert.equal(sends.length,1);assert.ok(s.events.some(event=>event[0]==="published"));assert.deepEqual(errors,[{event:"session_incident_restore_failed",vertical:"games",categoryId:"MLB1144"}]);assert.doesNotMatch(JSON.stringify(errors),/super-secret|database-password/);});

test("collectOnce logs an alert failure without replacing the affiliate error",async()=>{const affiliateError=Error("session_expired"),errors=[];await assert.rejects(()=>collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>{throw affiliateError;}},evolution:{},sessionAlert:{required:async()=>{throw Error("api-key=super-secret");},restored:async()=>{}},logger:{info(){},error:event=>errors.push(event)},dryRun:false}),error=>error===affiliateError);assert.deepEqual(errors,[{event:"session_alert_failed",vertical:"games",categoryId:"MLB1144"}]);assert.doesNotMatch(JSON.stringify(errors),/super-secret|api-key/);});

function batchStore(niches,{categories=[],recent=new Set()}={}){const events=[];let index=0;return{events,claimDueNiches:async()=>niches,nextCategory:async()=>categories[index++],recentItemIds:async()=>new Set(recent),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
const vertical=(id,categoryId)=>({...niche,id,categoryIds:[categoryId]});
const scoped=(categoryId,itemId,rank=0)=>({...candidate,itemId,categoryId,scopeCategoryId:categoryId,rank,title:`Oferta ${itemId}`,permalink:`https://produto.mercadolivre.com.br/${itemId}-oferta`});
test("publishes at most one offer from each rotated vertical",async()=>{const niches=[vertical("tools","MLB10"),vertical("sneakers","MLB20")],s=batchStore(niches,{categories:["MLB10","MLB20"],recent:new Set(["MLBOLD"])}),sends=[],waits=[];const source={list:async category=>[scoped(category,`${category}1`,0),scoped(category,`${category}2`,1)]};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"secret-token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},logger:{info(){},error(){}},dryRun:false,delay:async ms=>waits.push(ms),sendDelayMs:1000});assert.equal(result.published,2);assert.equal(sends.length,2);assert.deepEqual(waits,[1000,1000]);assert.deepEqual(s.events.filter(e=>e[0]==="published").map(e=>e[1]),["tools","sneakers"]);});
test("global history also blocks duplicates inside the current cycle",async()=>{const niches=[vertical("tools","MLB10"),vertical("sneakers","MLB20")],s=batchStore(niches,{categories:["MLB10","MLB20"]}),sends=[];const source={list:async category=>[scoped(category,"MLB1")]};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},dryRun:false,delay:async()=>{}});assert.equal(result.published,1);assert.equal(result.empty,1);assert.equal(sends.length,1);});
test("specific failures do not block later verticals and logs exclude secrets",async()=>{const niches=[vertical("bad-source","MLB10"),vertical("bad-affiliate","MLB20"),vertical("bad-delivery","MLB30"),vertical("good","MLB40")],s=batchStore(niches,{categories:["MLB10","MLB20","MLB30","MLB40"]}),logs=[];const source={list:async category=>{if(category==="MLB10")throw Error("source_unavailable");return[scoped(category,`${category}1`)]}};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"secret-token",meli:{convert:async url=>{if(url.includes("MLB20"))throw Error("session_expired");return"https://meli.la/ours";}},evolution:{send:async job=>{if(job.text.includes("MLB30"))throw Error("send");}},sessionAlert:{required:async()=>{},restored:async()=>{}},logger:{info:x=>logs.push(x),error:x=>logs.push(x)},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:4,published:1,review:3,empty:0});assert.deepEqual(s.events.filter(e=>e[0]==="complete").map(e=>e[2]),["source_error","affiliate_error","delivery_error","published"]);assert.equal(logs.length,4);assert.ok(logs.every(x=>x.vertical&&x.categoryId&&x.result));assert.doesNotMatch(JSON.stringify(logs),/secret-token/);});

test("collectDue awaits session restoration before delivery",async()=>{const niches=[vertical("tools","MLB10")],s=batchStore(niches,{categories:["MLB10"]}),restoreGate=deferred(),restoreEntered=deferred();let restored=false,sent=false;const collecting=collectDue({store:s,niches,source:{list:async category=>[scoped(category,"MLB10A")]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{sent=true;}},sessionAlert:{required:async()=>{},restored:async()=>{restoreEntered.resolve();await restoreGate.promise;restored=true;}},dryRun:false,delay:async()=>{}});await restoreEntered.promise;assert.equal(sent,false);restoreGate.resolve();assert.deepEqual(await collecting,{niches:1,published:1,review:0,empty:0});assert.equal(restored,true);assert.equal(sent,true);});

test("collectDue publishes a valid affiliate offer when incident restoration persistence fails",async()=>{const niches=[vertical("tools","MLB10")],s=batchStore(niches,{categories:["MLB10"]}),errors=[],sends=[];const result=await collectDue({store:s,niches,source:{list:async category=>[scoped(category,"MLB10A")]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},sessionAlert:{required:async()=>{},restored:async()=>{throw Error("database-password=super-secret");}},logger:{info(){},error:event=>errors.push(event)},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:1,published:1,review:0,empty:0});assert.equal(sends.length,1);assert.ok(s.events.some(event=>event[0]==="published"));assert.deepEqual(errors,[{event:"session_incident_restore_failed",vertical:"tools",categoryId:"MLB10"}]);assert.doesNotMatch(JSON.stringify(errors),/super-secret|database-password/);});

test("collectDue logs an alert failure and keeps the affiliate outcome",async()=>{const niches=[vertical("tools","MLB10")],s=batchStore(niches,{categories:["MLB10"]}),errors=[];const result=await collectDue({store:s,niches,source:{list:async category=>[scoped(category,"MLB10A")]},authorizedToken:async()=>"token",meli:{convert:async()=>{throw Error("session_expired");}},evolution:{},sessionAlert:{required:async()=>{throw Error("api-key=super-secret");},restored:async()=>{}},logger:{info(){},error:event=>errors.push(event)},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:1,published:0,review:1,empty:0});assert.deepEqual(s.events.filter(event=>event[0]==="complete").map(event=>event[2]),["affiliate_error"]);assert.deepEqual(errors,[{event:"session_alert_failed",vertical:"tools",categoryId:"MLB10"}]);assert.doesNotMatch(JSON.stringify(errors),/super-secret|api-key/);});

test("collectDue alerts again when a restored session expires later in the same round",async()=>{const niches=[vertical("first","MLB10"),vertical("restored","MLB20"),vertical("second","MLB30")],s=batchStore(niches,{categories:["MLB10","MLB20","MLB30"]}),required=[],restored=[];const result=await collectDue({store:s,niches,source:{list:async category=>[scoped(category,`${category}1`)]},authorizedToken:async()=>"token",meli:{convert:async url=>{if(!url.includes("MLB20"))throw Error("session_expired");return"https://meli.la/ours";}},evolution:{send:async()=>{}},sessionAlert:{required:async()=>required.push(true),restored:async()=>restored.push(true)},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:3,published:1,review:2,empty:0});assert.equal(required.length,2);assert.equal(restored.length,1);});
