import test from "node:test";
import assert from "node:assert/strict";
import { collectOnce, collectDue } from "../collector.mjs";
const niche={id:"games",categoryId:"MLB1144",destinationGroup:"d@g.us",tag:"tag",limit:1,enabled:true};
const candidate={itemId:"MLB1",rank:0,title:"Console",status:"active",permalink:"https://produto.mercadolivre.com.br/MLB-1-console",imageUrl:"https://http2.mlstatic.com/a.jpg",price:100,originalPrice:150,categoryId:"MLB1144"};
function store(){const events=[];return{events,claimDueNiche:async()=>niche,recentItemIds:async()=>new Set(),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
test("dry run persists preview without conversion or send",async()=>{const s=store();let external=0;const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>external++},evolution:{send:async()=>external++},dryRun:true});assert.equal(result,"simulated");assert.equal(external,0);assert.equal(s.events[0][3],"simulated");});
test("live run converts, sends image URL once, then publishes",async()=>{const s=store();const sends=[];const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async(job,media)=>sends.push({job,media})},dryRun:false});assert.equal(result,"published");assert.equal(sends.length,1);assert.equal(sends[0].media,candidate.imageUrl);assert.match(sends[0].job.text,/Publicidade/);assert.ok(s.events.some(e=>e[0]==="published"));});
test("ambiguous send is retained for review",async()=>{const s=store();const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{throw Error("send")}},dryRun:false});assert.equal(result,"review");assert.ok(s.events.some(e=>e[0]==="review"));});
test("session expiry raises the operator alert and successful conversion restores it",async()=>{const required=[],restored=[];const alert={required:async()=>required.push(true),restored:()=>restored.push(true)};await assert.rejects(()=>collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>{throw Error("session_expired")}},evolution:{},sessionAlert:alert,dryRun:false}),/session_expired/);assert.equal(required.length,1);await collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{}},sessionAlert:alert,dryRun:false});assert.equal(restored.length,1);});

function batchStore(niches,{categories=[],recent=new Set()}={}){const events=[];let index=0;return{events,claimDueNiches:async()=>niches,nextCategory:async()=>categories[index++],recentItemIds:async()=>new Set(recent),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
const vertical=(id,categoryId)=>({...niche,id,categoryIds:[categoryId]});
const scoped=(categoryId,itemId,rank=0)=>({...candidate,itemId,categoryId,scopeCategoryId:categoryId,rank,title:`Oferta ${itemId}`,permalink:`https://produto.mercadolivre.com.br/${itemId}-oferta`});
test("publishes at most one offer from each rotated vertical",async()=>{const niches=[vertical("tools","MLB10"),vertical("sneakers","MLB20")],s=batchStore(niches,{categories:["MLB10","MLB20"],recent:new Set(["MLBOLD"])}),sends=[],waits=[];const source={list:async category=>[scoped(category,`${category}1`,0),scoped(category,`${category}2`,1)]};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"secret-token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},logger:{info(){},error(){}},dryRun:false,delay:async ms=>waits.push(ms),sendDelayMs:1000});assert.equal(result.published,2);assert.equal(sends.length,2);assert.deepEqual(waits,[1000,1000]);assert.deepEqual(s.events.filter(e=>e[0]==="published").map(e=>e[1]),["tools","sneakers"]);});
test("global history also blocks duplicates inside the current cycle",async()=>{const niches=[vertical("tools","MLB10"),vertical("sneakers","MLB20")],s=batchStore(niches,{categories:["MLB10","MLB20"]}),sends=[];const source={list:async category=>[scoped(category,"MLB1")]};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},dryRun:false,delay:async()=>{}});assert.equal(result.published,1);assert.equal(result.empty,1);assert.equal(sends.length,1);});
test("specific failures do not block later verticals and logs exclude secrets",async()=>{const niches=[vertical("bad-source","MLB10"),vertical("bad-affiliate","MLB20"),vertical("bad-delivery","MLB30"),vertical("good","MLB40")],s=batchStore(niches,{categories:["MLB10","MLB20","MLB30","MLB40"]}),logs=[];const source={list:async category=>{if(category==="MLB10")throw Error("source_unavailable");return[scoped(category,`${category}1`)]}};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"secret-token",meli:{convert:async url=>{if(url.includes("MLB20"))throw Error("session_expired");return"https://meli.la/ours";}},evolution:{send:async job=>{if(job.text.includes("MLB30"))throw Error("send");}},sessionAlert:{required:async()=>{},restored:()=>{}},logger:{info:x=>logs.push(x),error:x=>logs.push(x)},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:4,published:1,review:3,empty:0});assert.deepEqual(s.events.filter(e=>e[0]==="complete").map(e=>e[2]),["source_error","affiliate_error","delivery_error","published"]);assert.equal(logs.length,4);assert.ok(logs.every(x=>x.vertical&&x.categoryId&&x.result));assert.doesNotMatch(JSON.stringify(logs),/secret-token/);});
