import test from "node:test";
import assert from "node:assert/strict";
import { collectOnce, collectDue } from "../collector.mjs";
const niche={id:"games",categoryId:"MLB1144",destinationGroup:"d@g.us",tag:"tag",limit:1,enabled:true};
const candidate={itemId:"MLB1",rank:0,title:"Console",status:"active",permalink:"https://produto.mercadolivre.com.br/MLB-1-console",imageUrl:"https://http2.mlstatic.com/a.jpg",price:100,originalPrice:150,categoryId:"MLB1144"};
function store(){const events=[];return{events,claimDueNiche:async()=>niche,recentItemIds:async()=>new Set(),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
test("dry run persists preview without conversion or send",async()=>{const s=store();let external=0;const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>external++},evolution:{send:async()=>external++},dryRun:true});assert.equal(result,"simulated");assert.equal(external,0);assert.equal(s.events[0][3],"simulated");});
test("live run converts, sends image URL once, then publishes",async()=>{const s=store();const sends=[];const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async(job,media)=>sends.push({job,media})},dryRun:false});assert.equal(result,"published");assert.equal(sends.length,1);assert.equal(sends[0].media,candidate.imageUrl);assert.match(sends[0].job.text,/Publicidade/);assert.ok(s.events.some(e=>e[0]==="published"));});
test("ambiguous send is retained for review",async()=>{const s=store();const result=await collectOnce({store:s,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{throw Error("send")}},dryRun:false});assert.equal(result,"review");assert.ok(s.events.some(e=>e[0]==="review"));});
test("session expiry raises the operator alert and successful conversion restores it",async()=>{const required=[],restored=[];const alert={required:async()=>required.push(true),restored:()=>restored.push(true)};await assert.rejects(()=>collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>{throw Error("session_expired")}},evolution:{},sessionAlert:alert,dryRun:false}),/session_expired/);assert.equal(required.length,1);await collectOnce({store:store(),source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{}},sessionAlert:alert,dryRun:false});assert.equal(restored.length,1);});

function batchStore(niches){const events=[];return{events,claimDueNiches:async()=>niches,recentItemIds:async()=>new Set(),savePreview:async(...a)=>events.push(["preview",...a]),completeRun:async(...a)=>events.push(["complete",...a]),markPublished:async(...a)=>events.push(["published",...a]),markReview:async(...a)=>events.push(["review",...a])};}
test("publishes bounded batches across all due niches",async()=>{const niches=[{...niche,id:"technology",categoryId:"MLB1000",limit:2},{...niche,id:"games",categoryId:"MLB1144",limit:2}],s=batchStore(niches),sends=[],waits=[];const source={list:async category=>[0,1].map(rank=>({...candidate,itemId:`${category}${rank}`,categoryId:category,scopeCategoryId:category,rank}))};const result=await collectDue({store:s,niches,source,authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async job=>sends.push(job)},dryRun:false,delay:async ms=>waits.push(ms),sendDelayMs:1000});assert.deepEqual(result,{niches:2,published:4,review:0,empty:0});assert.equal(sends.length,4);assert.deepEqual(waits,[1000,1000,1000,1000]);});
test("one failed conversion does not block later batch items and alerts once",async()=>{const niches=[{...niche,limit:2}],s=batchStore(niches),sends=[],alerts=[];let calls=0;const result=await collectDue({store:s,niches,source:{list:async()=>[candidate,{...candidate,itemId:"MLB2",rank:2}]},authorizedToken:async()=>"token",meli:{convert:async()=>{if(calls++===0)throw Error("session_expired");return"https://meli.la/ours";}},evolution:{send:async job=>sends.push(job)},sessionAlert:{required:async()=>alerts.push(1),restored:()=>{}},dryRun:false,delay:async()=>{}});assert.deepEqual(result,{niches:1,published:1,review:1,empty:0});assert.equal(sends.length,1);assert.equal(alerts.length,1);assert.ok(s.events.some(e=>e[0]==="review"&&e[2]==="MLB1"));});
test("ambiguous batch delivery is reviewed without publication",async()=>{const niches=[{...niche,limit:1}],s=batchStore(niches);const result=await collectDue({store:s,niches,source:{list:async()=>[candidate]},authorizedToken:async()=>"token",meli:{convert:async()=>"https://meli.la/ours"},evolution:{send:async()=>{throw Error("send")}},dryRun:false,delay:async()=>{}});assert.equal(result.review,1);assert.equal(result.published,0);assert.ok(!s.events.some(e=>e[0]==="published"));});
